/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface I18N {
  page?: {
    title?: string;
    description?: string;
    privacy?: string;
    legal_notice?: string;
    licenses?: string;
    contact?: string;
    learn_more?: string;
    [k: string]: any;
  };
  header?: {
    home?: string;
    about?: string;
    projects?: string;
    contact?: string;
    contact_us?: string;
    [k: string]: any;
  };
  footer?: {
    build_with?: string;
    by_team_and?: string;
    contributers?: string;
    rights_reserved?: string;
    [k: string]: any;
  };
  homepage?: {
    title?: string;
    description?: string;
    mission?: {
      title_part1?: string;
      title_highlighted?: string;
      title_part2?: string;
      description_part1?: string;
      description_part2?: string;
      learn_more?: string;
      learn_more_link?: string;
      [k: string]: any;
    };
    core_values?: {
      title_part1?: string;
      title_highlighted?: string;
      description?: string;
      privacy?: {
        title?: string;
        description?: string;
        [k: string]: any;
      };
      transparency?: {
        title?: string;
        description?: string;
        [k: string]: any;
      };
      security?: {
        title?: string;
        description?: string;
        [k: string]: any;
      };
      tracking?: {
        title?: string;
        description?: string;
        [k: string]: any;
      };
      [k: string]: any;
    };
    open_source?: {
      title_part1?: string;
      title_highlighted?: string;
      subtitle?: string;
      description?: string;
      learn_more?: string;
      learn_more_link?: string;
      [k: string]: any;
    };
    [k: string]: any;
  };
  contact?: {
    page_title?: string;
    page_description?: string;
    title?: string;
    title_highlighted?: string;
    description?: string;
    video_call?: {
      title?: string;
      description?: string;
      form_subject?: string;
      form_message?: string;
      [k: string]: any;
    };
    email?: {
      title?: string;
      description?: string;
      [k: string]: any;
    };
    form?: {
      email?: string;
      email_placeholder?: string;
      subject?: string;
      subject_placeholder?: string;
      message?: string;
      message_placeholder?: string;
      privacy_notice?: string;
      privacy_notice_link?: string;
      send?: string;
      success?: string;
      error?: string;
      warning?: string;
      success_description?: string;
      success_back_button?: string;
      [k: string]: any;
    };
    [k: string]: any;
  };
  projects?: {
    page_title?: string;
    page_description?: string;
    title?: string;
    title_highlighted?: string;
    description?: string;
    coming_soon?: string;
    launched_previously?: string;
    worktime_tracker?: {
      title?: string;
      description?: string;
      linkText?: string;
      [k: string]: any;
    };
    activehq?: {
      title?: string;
      description?: string;
      linkText?: string;
      [k: string]: any;
    };
    travelventures?: {
      title?: string;
      description?: string;
      linkText?: string;
      [k: string]: any;
    };
    opensource?: {
      title?: string;
      description?: string;
      linkText?: string;
      [k: string]: any;
    };
    [k: string]: any;
  };
  not_found?: {
    page_title?: string;
    page_description?: string;
    title?: string;
    link?: string;
    [k: string]: any;
  };
  test?: {
    helloworld?: string;
    [k: string]: any;
  };
  [k: string]: any;
}
